# Generated by Django 4.2.5 on 2024-11-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
