# Generated by Django 4.2.5 on 2024-12-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encor_app', '0002_plan_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
