# Generated by Django 4.2.5 on 2024-12-06 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encor_app', '0003_request_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Offer',
        ),
    ]
